name: Build UWP App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1.3
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1
    
    - name: Restore NuGet packages
      run: nuget restore AllLive.sln
    
    - name: Build Core library
      run: msbuild AllLive.Core/AllLive.Core.csproj /p:Configuration=Release /p:Platform="Any CPU"
    
    - name: Build Console App
      run: msbuild AllLive.Console/AllLive.ConsoleApp.csproj /p:Configuration=Release /p:Platform="Any CPU"
    
    - name: Build UWP App
      run: msbuild AllLive.UWP/AllLive.UWP.csproj /p:Configuration=Release /p:Platform=x64 /p:TargetPlatformVersion=10.0.19041.0 /p:TargetPlatformMinVersion=10.0.18362.0
    
    - name: Create UWP App Package
      run: msbuild AllLive.UWP/AllLive.UWP.csproj /p:Configuration=Release /p:Platform=x64 /p:UapAppxPackageBuildMode=StoreUpload /p:TargetPlatformVersion=10.0.19041.0 /p:TargetPlatformMinVersion=10.0.18362.0
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AllLive-UWP-Package
        path: AllLive.UWP\AppPackages
        retention-days: 30